language: python

dist: xenial

cache:
  directories:
    - $HOME/.cache/pip

python:
  - "3.6"

matrix:
  include:
    - os: osx
      language: generic
    - os: linux

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then HOMEBREW_NO_AUTO_UPDATE=1 brew install md5sha1sum; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source $HOME/miniconda/etc/profile.d/conda.sh
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels bioconda --add channels conda-forge
  - conda info -a
  - wget https://export.uppmax.uu.se/uppstore2018173/blr-testdata-0.1.tar.gz
  - tar xf blr-testdata-0.1.tar.gz
  - ln -s blr-testdata-0.1 testdata
  - printf "bowtie2_reference: %s\npicard_command: picard%s\n" "$PWD/testdata/chr1mini" >> tests/test_config.yaml

install:
  - conda env create -n testenv -f environment.yml
  - conda activate testenv
  - pip install .

script: tests/run.sh
