language: generic

dist: xenial

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then HOMEBREW_NO_AUTO_UPDATE=1 brew install md5sha1sum; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source $HOME/miniconda/etc/profile.d/conda.sh
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels bioconda --add channels conda-forge
  - conda info -a
  - wget https://export.uppmax.uu.se/uppstore2018173/blr-testdata-0.2.tar.gz
  - tar xf blr-testdata-0.2.tar.gz
  - ln -s blr-testdata-0.2 testdata

install:
  - conda env create -n testenv -f environment.${TRAVIS_OS_NAME}.lock.yml
  - conda activate testenv
  - conda install pytest
  - pip install --no-deps .

script:
  - tests/run.sh

jobs:
  include:
    - name: Linux
      os: linux
    - name: macOS
      os: osx
    - name: flake8
      language: python
      python: "3.6"
      before_install:
      install: python3 -m pip install flake8
      script: flake8 src/ tests/
