$schema: "http://json-schema.org/draft-06/schema#"
description: Configuration parameters for running BLR pipeline
properties:
  index_nucleotides:
    type: integer
    description: Number of index nucleotide to use when splitting for barcode clustering.
    default: 3
  heap_space:
    type: integer
    description: Heap space to use for picard commands.
    default: 90
  cluster_tag:
    type: string
    description: SAM tag to use for store barcode cluster id in bam file. 'BX' is 10x genomic default
    default: BX
  molecule_tag:
    type: string
    description: SAM flag used to store molecule ID, same as 10x default.
    default: MI
  num_mol_tag:
    type: string
    description: SAM flag used to store number of molecules per barcode.
    default: MN
  sequence_tag:
    type: string
    description: SAM tag to use for store original barcode sequence in bam file. 'RX' is 10x genomic default
    default: RX
  bowtie2_reference:
    type: string
    description: Path to bowtie2 reference for mapping
    default: .
  picard_command:
    type: string
    description: Picard command to be used.
    default: picard
  hapcut2:
    type: string
    description: Hapcut2 command to be used.
    default: .
  reference_variants:
    type: string
    description: Path to reference variants, if not provided then variant will be called by freebayes
    default:
  phasing_ground_truth:
    type: string
    description: Path to phased variants used to compute phasing stats.
    default: .