# Whenever this file is updated, you need to run misc/condalock.sh to create
# the environment.lock.yml file.

channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nomkl
  - python=3.6
  - bowtie2
  - bwa
  - minimap2
  - pysam
  - cutadapt=2.5
  - sambamba=0.6.6
  - samblaster
  - hapcut2=1.2
  - samtools
  - snakemake-minimal
  - starcode
  - tqdm
  - importlib_resources
  - freebayes
  - ruamel.yaml
  - vcflib
  - ema=0.6.2
  - fastqc
  - multiqc
  - bcftools
  - gatk4
  - pandas